### ISSUE TITLE
Error after successful payment

### ISSUE THREAD

**Issue by uche40** [Kendysond/Wordpress-Paid-Membership-Pro-Paystack#1]
Error after successful payment, tried with multiple bank accounts...here is a screenshot
![invalid reference](https://user-images.githubusercontent.com/8086604/29983601-9afefdba-8f4e-11e7-8e4a-ad4a5d018c38.png)

**Comment by Kendysond** [comment]
Hi @uche40 

Apologies for the confusion. That error actually means your server was unable to verify the payment was successful. 

Here's what happens after a payment: 
- The user gets redirected with the transaction reference to your website. 
- You website/server calls Paystack's api to verify the transaction was actually successful before it gives the user a membership subscription. 

In your case, your website/server is unable to perform the second action. This could be caused by a number of reasons, outdated CURL version, cloudflare block, e.t.c 

I suggest you reach out to the Paystack team via hello@paystack.com or join their slack channel @ slack.paystack.com, they'll be happy to assist in the resolution of this issue. 

I hope this helps.
